[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
cache_path = 'cache_forge'
remappings = [
	'@cwia/=node_modules/clones-with-immutable-args',
	'safe-contracts=node_modules/@safe-global/safe-smart-account/contracts'
]
